### ISSUE TITLE
FacebookDebugTokenResponse.cs is not found

### ISSUE THREAD

**Issue by EnterpriseWide** [abjerner/Skybrud.Social#18]
Hey there,
Just looking around and found this file included in the solution but missing from source. Thanks for the library BTW. #h5yr
Error	1	Source file 'Facebook\Responses\Debug\FacebookDebugTokenResponse.cs' could not be found	C:\Users\abjerner_wannabe\Documents\work\Skybrud.Social\src\Skybrud.Social\CSC	Skybrud.Social

**Comment by abjerner** [comment]
Sorry about that. The `Debug` folder is ignored by the `.gitignore` file, so the file had to be added manually. I have done that now, so compiling works again ;)
