### ISSUE TITLE
How to access the google web analytics data

### ISSUE THREAD

**Issue by arun6012** [abjerner/Skybrud.Social#19]
Hi,

Could please provide some sample code, how to authenticate and get the data from Google web analytics?

I want create a dashboard with chart options for one web site analytics, can you please help me how to use your dll for Google analytics. 

Thanks,

**Comment by abjerner** [comment]
I don't know how much you have working so far. If you don't already have an access token or refresh token, you can have a look at this Gist, which shows how to setup basic authentication in WebForms:

https://gist.github.com/abjerner/9eea20afc4ba108ef83b

Communication with the Google APIs starts with the `GoogleService` class. Once you have a valid access token, you can get an instance as:

```C#
GoogleService service = GoogleService.CreateFromAccessToken(accessToken);
```

If you instead have a refresh token, you can get an instance of `GoogleService` as:

```C#
GoogleService service = GoogleService.CreateFromRefreshToken(clientId, clientSecret, refreshToken);
```

For the Analytics API, you then need the Analytics endpoint:

```C#
AnalyticsEndpoint analytics = service.Analytics;
```

**Getting a list of Analytics accounts**
A Google account may have multiple Analytics accounts. You can get a list of them as:

```C#
foreach (AnalyticsAccount account in analytics.GetAccounts().Items) {
    string accountId = account.Id;
    string accountName = account.Name;
}
```

**Getting a list of web properties**
Each account may also have multiple web properties. You can get a list of all of them across all your Analytics accounts as:

```C#
foreach (AnalyticsWebProperty webProperty in analytics.GetWebProperties().Items) {
    string webPropertyId = webProperty.Id;
    string webPropertyName = webProperty.Name;
}
```

Or for a specific Analytics account as:

```C#
foreach (AnalyticsWebProperty webProperty in analytics.GetWebProperties(accountId).Items) {
    string webPropertyId = webProperty.Id;
    string webPropertyName = webProperty.Name;
}
```

**Getting a list of profiles**
Similar to an account, a web property may have one ore more profiles (or none at all). You can list all profiles as:

```C#
foreach (AnalyticsProfile profile in analytics.GetProfiles().Items) {
    string profileId = profile.Id;
    string profileName = profile.Name;
}
```

All profiles for a given account as:

```C#
foreach (AnalyticsProfile profile in analytics.GetProfiles(accountId).Items) {
    string profileId = profile.Id;
    string profileName = profile.Name;
}
```

Or for a specific web property as:

```C#
foreach (AnalyticsProfile profile in analytics.GetProfiles(accountId, webPropertyId).Items) {
    string profileId = profile.Id;
    string profileName = profile.Name;
}
```

**Getting data from a profile**

Getting data has a lot of options. In the example below, we get data for `profileId` for the last month. The data returned is `AnalyticsMetric.Visits` and `AnalyticsMetric.Pageviews` grouped by `AnalyticsDimension.Date`.

```C#
AnalyticsDataResponse data = analytics.GetData(
    profileId,
    DateTime.Now.AddDays(-31),
    DateTime.Now,
    AnalyticsMetric.Visits + AnalyticsMetric.Pageviews,
    AnalyticsDimension.Date
);
```
You can also use the `AnalyticsDataOptions` class. While the class has more properties for advanced use, the example below will do the same as above:

```C#
AnalyticsDataOptions options = new AnalyticsDataOptions {
    StartDate = DateTime.Now.AddDays(-31),
    EndDate = DateTime.Now,
    Dimensions = AnalyticsDimension.Date,
    Metrics = AnalyticsMetric.Visits + AnalyticsMetric.Pageviews
};

AnalyticsDataResponse data = analytics.GetData(profileId, options);
```

You can then iterate over the data as (dimensions are listed first, then metrics):

```C#
foreach (AnalyticsDataColumnHeader column in data.ColumnHeaders) {
    Console.Write((column.Name + " (" + column.DataType + ")").PadRight(32));
}
Console.WriteLine();

foreach (AnalyticsDataRow row in data.Rows) {
    foreach (string cell in row.Cells) {
        Console.Write(cell.PadRight(32));
    }
    Console.WriteLine();
}
```

Also if you're willing to play around with the most recent (but yet unreleased) code from the repository, you can call `GetString` and `GetInt32` directly on the row:

```C#
foreach (AnalyticsDataRow row in data.Rows) {

    // Get the date (both calls give the same result)
    string date1 = row.GetString(AnalyticsDimension.Date);
    string date2 = row.GetString("ga:date");

    int visits = row.GetInt32(AnalyticsMetric.Visits);
    int pageviews = row.GetInt32(AnalyticsMetric.Pageviews);

    // Almost as before, but cell is now an object rather than a string
    foreach (AnalyticsDataCell cell in row.Cells) {
        Console.Write(cell.Value.PadRight(32));
    }
                    
    Console.WriteLine();
                
}
```

Let me know if this helps you out ;)
