### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by EnterpriseWide** [abjerner/Skybrud.Social#20]
Hey there, How close do you think you are to a new release?
Do you have a list of things to do?

**Comment by abjerner** [comment]
I'm actually working on the last bits for the next release now, and it will be released either tonight or some time tomorrow (Danish time) depending on how long time it takes. The next release will be `v0.9.0`, which will be very similar to the `v0.9.0-alpha1` released a few days ago.

Regarding plans, my main goal towards `v1.0` is that all endpoint methods should return an object representing the entire response from the service/API in question, rather than just an object representing the response body. As an example, a method for getting information about a Twitter user should return an instance of `TwitterUserResponse` rather than `TwitterUser`. The `Body` property of `TwitterUserResponse` will then be of the type `TwitterUser`.

It takes some time to update the entire codebase to follow this structure, so not all methods in `v0.9.0` has been updated yet, but they will be so in `v1.0`. Since this is a major change that has taken some time until now, I don't really have any specific plans after that. I usually just add features as I need them, or people ask for them.

Is there anything specific that you need?

**Comment by EnterpriseWide** [comment]
im after paging against the facebook and instragram implementations at the moment but will be after twitter and google probably later. I notice both of those have been active and that instagram now has that. Sample code doing paging for both of those would be great.

**Comment by abjerner** [comment]
Hi. I have now released `v0.9.0` ;)

Most endpoint methods already support pagination if it is supported in the underlying API. Pagination works a little different from method to method - even for the same API. Is there any specific methods you're trying to use with pagination? Then I can try to post some documentation here.

Anyways, I'm working on a new website for Skybrud.Social somewhat simultaneously with Skybrud.Social itself. The new website will have an improved documentation and lots of examples, so at least pagination will be covered there. ETA is probably a couple of weeks from now.

**Comment by EnterpriseWide** [comment]
Hey Anders,
I am using 2 . First is instagram recent media and second is facebook posts

Instagram ...

            var authorisationValue = app.GetValue<string>("authorisation");
            var instagram =
InstagramOAuthData.Deserialize(authorisationValue);
            if (instagram != null && instagram.IsValid)
            {
                var service = instagram.GetService();
                var user = null as InstagramUserSummary;
...
                    user = service.Users.Search(identifier)
                        .Body
                        .Data
                        .FirstOrDefault(i => i.Username.ToLower() ==
identifier);
                    if (user != null)
                    {
                        InstagramRecentMediaResponse response = null;
                        var moreItems = false;
                        try
                        {
                            response =
service.Users.GetRecentMedia(user.Id, count * 3);
                            moreItems = true;
                        }
                        catch { }
                        while (mediaItems.Count < count && moreItems)
                        {
                            moreItems =
!string.IsNullOrEmpty(response.NextMaxId);
                            var images = response.Media;
                            if (!string.IsNullOrEmpty(hashTag))
                            {
                                mediaItems.AddRange(images.Where(i =>
i.Tags.Contains(hashTag)));
                            }
                            else
                            {
                                mediaItems.AddRange(images);
                            }
                            if (mediaItems.Count < count && moreItems)
                            {
                                response =
service.Users.GetRecentMedia(user.Id, new InstagramUserRecentMediaOptions {
MaxId = response.NextMaxId, Count = count * 3 });
                            }
                        };
                    }

Facebook ...
            var authorisationValue = app.GetValue<string>("authorisation");
            var socialFeed =
FacebookOAuthData.Deserialize(authorisationValue);
            var service = socialFeed.GetService();
            var user = service.Users.GetUser().Body;
            if (socialFeed != null && socialFeed.IsValid)
            {
                var posts = service.Posts.GetPosts(user.Id, count * 3)
                    .Body
                    .Data;
                mediaItems.AddRange(posts);
            }

Regards


On Sat, Feb 14, 2015 at 5:04 AM, Anders Bjerner <notifications@github.com>
wrote:

> Hi. I have now released v0.9.0 ;)
>
> Most endpoint methods already support pagination if it is supported in the
> underlying API. Pagination works a little different from method to method -
> even for the same API. Is there any specific methods you're trying to use
> with pagination? Then I can try to post some documentation here.
>
> Anyways, I'm working on a new website for Skybrud.Social somewhat
> simultaneously with Skybrud.Social itself. The new website will have an
> improved documentation and lots of examples, so at least pagination will be
> covered there. ETA is probably a couple of weeks from now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abjerner/Skybrud.Social/issues/20#issuecomment-74297684>
> .
>



-- 
[image: Liquid Visual] <http://ewide.com.au/>Ben NormanWeb Developer / .NET
Specialiste  support@ewide.biz  t  (+61) 404 828 246
w  ewide.com.au

**Comment by abjerner** [comment]
**Facebook posts**
I can see that you're using my Umbraco package. The package still uses `v0.1.2`, so pagination isn't fully supported.

I can't see exactly what your trying to do, but for Facebook posts the maximum limit allowed by the API is 250 posts, so perhaps you don't need pagination at all? Anyways, in `v0.1.2` you can do something like:

```C#
FacebookPostsResponse response = service.Methods.GetPosts(user.Id, 250);

mediaItems.AddRange(response.Data);
```

In `v0.9.0` you can do something like the example below. When fetching posts Facebook uses what they call time-based pagination, which basically is that to get older posts, you simply specify the timestamp for when the last post on the first page was created.

```C#
// Get the first 250 posts on the first page
FacebookPostsResponse response = service.Posts.GetPosts(user.Id, new FacebookPostsOptions {
    Limit = 250
});

// Add the posts the the collection
mediaItems.AddRange(response.Body.Data);

// If the "Until" property isn't NULL, we fetch the next page
if (response.Body.Paging.Until != null) {
            
    // Get the next 250 posts
    response = service.Posts.GetPosts(user.Id, new FacebookPostsOptions {
        Limit = 250,
        Until = response.Body.Paging.Until.Value
    });
                
    // Add the posts the the collection
    mediaItems.AddRange(response.Body.Data);
            
}
```

However time-based pagination has some downsides. In the example above, the last post of the first page will also be a part of the posts returned for the next request since the timestamp is the same. So you need to do some kind of union (check that the post is not already in your list).

You could also just set the timestamp to one second earlier, but then you risk loosing posts if the last post in the first response shares the same timestamp as the next post (which probably isn't that likely).

```C#
// Get the next 250 posts
response = service.Posts.GetPosts(user.Id, new FacebookPostsOptions {
    Limit = 250,
    Until = response.Body.Paging.Until.Value - 1
});
```

**Comment by abjerner** [comment]
**Instagram**

Again, I'm not 100% sure what you're trying to do. It seems that your doing the pagination right, but from what I can tell, your if statements results in only the first request being sent.

If you're trying to fetch the first X amount of posts for a given user, you can do something like the code below (in `v0.9.0` that is):

```C#
string nextMaxId = null;

do  {

    InstagramRecentMediaResponse response = service.Users.GetRecentMedia(user.Id, new InstagramUserRecentMediaOptions {
        Count = count,
        MaxId = nextMaxId
    });

    nextMaxId = response.NextMaxId;

    if (!string.IsNullOrEmpty(hashTag)) {
        mediaItems.AddRange(response.Images.Where(i => i.Tags.Contains(hashTag)));
    } else {
        mediaItems.AddRange(response.Images);
    }

} while (!String.IsNullOrWhiteSpace(nextMaxId) && mediaItems.Count < totalCount);
```

In `v0.1.2` simply replace the class name `InstagramUserRecentMediaOptions`with `InstagramMediaSearchOptions`.

**Comment by abjerner** [comment]
Also in both your Facebook and Instagram code, you're making a lookup on the authenticated user. Unless you have a specific reason for this, it shouldn't be necessary.

For Facebook you can simply replace the user ID with `me` (which is a magical constant referring to the authenticated user):

```C#
FacebookPostsResponse response = service.Methods.GetPosts("me", 250);
```

In Instagram, you can simply change:

```C#
InstagramRecentMediaResponse response = service.Users.GetRecentMedia(user.Id, new InstagramUserRecentMediaOptions {
    Count = count,
    MaxId = nextMaxId
});
```

to:

```C#
InstagramRecentMediaResponse response = service.Users.GetRecentMedia(new InstagramUserRecentMediaOptions {
    Count = count,
    MaxId = nextMaxId
});
```

**Comment by EnterpriseWide** [comment]
This is what I did to get paging working on facebook:

thanks for the pointers
```
            var mediaItems = new List<FacebookPost>();
            if (socialFeed != null && socialFeed.IsValid)
            {
                var options = new FacebookPostsOptions
                {
                    Limit = 5
                };
                do
                {
                    var response = service.Posts.GetPosts("me", options);
                    var list = response.Body.Data as IEnumerable<FacebookPost>;
                    if (string.IsNullOrEmpty(hashTag))
                    {
                    // cant tell if its an initiating post or a comment so remove all posts that are not videos or photos
                        list = list.Where(i => i.Type != "status");
                    }
                    else
                    {
                        list = list.Where(i => (i.Message ?? String.Empty).Contains(hashTag));
                    }
                    mediaItems.AddRange(list);
                    if (response.Body.Paging != null && response.Body.Paging.Until != null)
                    {
                        options.Until = response.Body.Paging.Until.Value - 1;
                    }
                    else
                    {
                        options = null;
                    }
                } while (options != null && mediaItems.Count < count);
        }
```
