### ISSUE TITLE
pictures from facebook

### ISSUE THREAD

**Issue by EnterpriseWide** [abjerner/Skybrud.Social#21]
Do you know how to get images from facebook for posts with a video in it?
Do I need to make another call to get the thumbnail for the video?
I currently make the following call and the picture that comes back is not returning any data :(

var posts = service.Posts.GetPosts(user.Id, 50).Body.Data;

**Comment by abjerner** [comment]
If a post contains a video, the URL of a thumbnail or screenshot will be available through `post.Picture`. 

I don't think there is a way to lookup the size of the image other than downloading the image file and checking the file size from your own code.
