### ISSUE TITLE
Add CreateFromClientId method to InstagramService class.

### ISSUE THREAD

**Issue by abjerner** [abjerner/Skybrud.Social#24]
The `InstagramService` class can currently only be initialized by calling either `CreateFromAccessToken(string accessToken)` or `CreateFromOAuthClient(InstagramOAuthClient client)`.

Since it is possible to use a client ID instead of an access token, a `CreateFromClientId(string clientId)` method should be implemented as well.

**Comment by abjerner** [comment]
Fixed and will be a part of the next release :D

**Comment by glaidler** [comment]
Hi, according to the current Instagram API docs, all requests require an access_token.  Using this method passes a client_id for subsequent requests and throws an invalid access_token exception.  Is this method of authentication now deprecated by instagram?

**Comment by abjerner** [comment]
Hi Graham,

To my knowledge it should still work, but I will look into whether Instagram has changed something that affects this.

However not all methods in the API support using a client ID. What API methods are you trying to call?

**Comment by glaidler** [comment]
Hi - even the one to retrieve media from a known user requires an access_token:
https://www.instagram.com/developer/endpoints/users/#get_users_media_recent

**Comment by abjerner** [comment]
Then it might be due to [this update](http://developers.instagram.com/post/133424514006/instagram-platform-update) although they don't write so explicitly.

**Comment by abjerner** [comment]
Just to confirm. This is due to a change by Instagram. If you register a new app, you will automatically be limited by the new "rules", which among other things mean that you can't use a client ID.

I you have an old app - that is registered before the 17th of November, you will still follow the old rules, which means you can continue to use the client ID as before - at least until June 2016.

New apps should also be submitted for review before they can be used by your users. I have only just skimmed the details about the new changes. Maybe you will still be able to use your client ID once your app has been approved.
