### ISSUE TITLE
"Source" missing from Skybrud.Social.Facebook.Objects.Posts.FacebookPost

### ISSUE THREAD

**Issue by seanhak** [abjerner/Skybrud.Social#26]
Hi!
I need to access the "Source" graph property to get access the video uploaded to my feed. (/me/feed)

**Comment by abjerner** [comment]
Hi Sean,

I will make sure to add the property for the next release.

Meanwhile, since the objects expose the underlying JSON, you should be able to access the source property like:

`post.JsonObject.GetString("source")`

**Comment by seanhak** [comment]
Cool! Really nice project, i hate having 5 different nugets with all different dependencies and versions.
I'm afraid I'm a bit lost without documentation, had to switch to c# sdk :( 
Is there a method to call any graph object "directly", i.e. FacebookService Api("/graphid/")

**Comment by abjerner** [comment]
Hi again,

Sorry for the lack of documentation. I'm currently building a new website for Skybrud.Social, which will feature a greatly improved documentation. It will be online very soon ;)

If you already have an instance of `FacebookService` (or `FacebookClient` really), you can do something like:

```C#
NameValueCollection query = new NameValueCollection {
    {"limit", "5"}        
};

SocialHttpResponse response = service.Client.DoAuthenticatedGetRequest("/me/feed", query);

string json = response.Body;
```

You can then manually parse the JSON with either my `JsonObject` class as a starting point or by using Newtonsoft.Json ;)

When you use the `DoAuthenticatedGetRequest` method and the specified URL starts with a forward slash, the code will automatically prefix the domain and API version. So if you specify `/me/feed`, the code will make a request to `https://graph.facebook.com/v2.2/me/feed`. Also, the access token will be appended to the query string automatically.

Given your other issue (#27) regarding specifying a locale, you could use the following code:

```
NameValueCollection query = new NameValueCollection {
    {"limit", "5"},
    {"locale", "da_DK"}
};

SocialHttpResponse response1 = service.Client.DoAuthenticatedGetRequest("/me/feed", query);

FacebookFeedResponse response2 = FacebookFeedResponse.ParseResponse(response1);
```

**Comment by seanhak** [comment]
Million thanks!
By the way, the reason I need the documentation is not because bad code or anything, its just that I'm a frontend guy who likes to experiment with c#/razor from time to time, no need to apologize.
That said, I'm really looking forward to your new skybrud.social site :)
Please let me donate that domain name as a thank you!

**Comment by abjerner** [comment]
Thanks for the feedback.

I have now implemented the `Source` property in both the `FacebookFeedEntry` and the `FacebookPost` classes. I will see whether I can find the time to push out a new release some time in the coming week ;)

My reason for apologizing was mostly because I'm not satisfied with the amount of documentation myself. A project like this should have better documentation.

Regarding a domain name, the new site will simply replace the current site at http://social.skybrud.dk/ so no reason to buy a new domain name. But thanks for the offer ;)

**Comment by abjerner** [comment]
Hi Sean,

I have now pushed a new release where the `Source` property has been added ;)
