### ISSUE TITLE
Facebook localisation

### ISSUE THREAD

**Issue by seanhak** [abjerner/Skybrud.Social#27]
Are there any options to specify locale output?

/me/feed?**locale=sv_SE**

**Comment by abjerner** [comment]
Hi Sean,

I haven't really looked into localization yet, so this is not something that is supported.

Do you have by any chance have some examples where localization makes sense?

**Comment by seanhak** [comment]
Hi!
It's basically appending locale=xx_XX for every graph request.

Scope: /me/feed
"story": "Seanhak uploaded a new video.",

With locale=da_DK
"story": "Seanhak overf\u00f8rte en ny video"

I guess I could also check "status_type", and use Umbraco dictionary for different cases.

**Comment by abjerner** [comment]
Thanks. I will make sure to add an option for that to the next release ;)

Meanwhile you could change your code to something like:

```
NameValueCollection query = new NameValueCollection {
    {"limit", "5"},
    {"locale", "da_DK"}
};

SocialHttpResponse response1 = service.Client.DoAuthenticatedGetRequest("/me/feed", query);

FacebookFeedResponse response2 = FacebookFeedResponse.ParseResponse(response1);
```

**Comment by abjerner** [comment]
Hi again,

I have now pushed a new release where this is supported.

I have added a `Locale` property to the `FacebookOAuthClient` class, so you can use it like:

```C#
client.Locale = "da_DK";
```

or

```C#
service.Client.Locale = "da_DK";
```

The locale is then used for all request to the Graph API ;)
