### ISSUE TITLE
Is't possible to use the package to login with social with Umbraco membership?

### ISSUE THREAD

**Issue by biapar** [abjerner/Skybrud.Social#28]
Is't possible to use the package to login with social with Umbraco membership?

**Comment by abjerner** [comment]
Hi Biagio,

Yes and no. It is not something that is supported by this package - at least not out of the box - so you will have to do some work on your own.

I can see that you have posted a similar question for [my package on Umbraco Our](https://our.umbraco.org/projects/website-utilities/skybrudsocial-for-umbraco-7/general-discussion/65012-Ist-possible-to-use-this-pack-for-social-authetication-with-Umbraco). My **Skybrud.Social for Umbraco 7** package brings some of the features of **Skybrud.Social** to Umbraco, but nothing for members.

I know that [Lee](https://github.com/leen3o) has done something similar to what you're describing for his [Dialogue-package](https://github.com/leen3o/Dialogue). His package uses Skybrud.Social to allow members to login via either Facebook or Google, so my advice would be to look at his source code ;)

These classes might help you out:

https://github.com/leen3o/Dialogue/blob/master/Src/Dialogue.Logic/Controllers/OAuthControllers/FacebookOAuthSurfaceController.cs
https://github.com/leen3o/Dialogue/blob/master/Src/Dialogue.Logic/Controllers/OAuthControllers/GoogleOAuthSurfaceController.cs
