### ISSUE TITLE
Parsing of class "FacebookUser" fails if gender isn't specified in the JSON

### ISSUE THREAD

**Issue by abjerner** [abjerner/Skybrud.Social#30]

**Comment by abjerner** [comment]
Fixed :D

**Comment by chandrashekharkhod** [comment]
Hello,
I've changed as above, Now I'm getting error about email access.
Unable to get email access

**Comment by abjerner** [comment]
@chandrashekharkhod I'm not sure that I understand - what have you changed? And how do you get an error about the email address? Is this an error (exception) from Skybrud.Social or an error shown by MvcForum?

**Comment by chandrashekharkhod** [comment]
Hello,

Thank you for quick reply, I've changed in JsonObject.cs as below link:
https://github.com/abjerner/Skybrud.Social/commit/6100a9e577133038c04b6cda5a9f88d3a248a54e

**Comment by abjerner** [comment]
@chandrashekharkhod Alrighty.

If Facebook doesn't respond with an email address in the JSON for a given user, the `Email` property should simply return `null`.

How exactly do you see the error about the email address? I'm thinking it is more an issue with MvcForum (since user creation might require an email address).

The more information you're able to provide, the easier it is for me to find out whether this is an issue in Skybrud.Social, and if so, fix it.
