### ISSUE TITLE
Instagram tags endpoint missing search

### ISSUE THREAD

**Issue by fedrch** [abjerner/Skybrud.Social#36]
Missing api fearture https://instagram.com/developer/endpoints/tags/#get_tags_search

**Comment by abjerner** [comment]
Thanks for reporting. I will make sure to add that for the next release ;)

**Comment by abjerner** [comment]
This was implemented a few days ago, so if you pull down the latest code, you will be able to do something like:

```C#
@using Skybrud.Social.Instagram
@using Skybrud.Social.Instagram.Objects
@using Skybrud.Social.Instagram.Responses
@inherits System.Web.Mvc.WebViewPage<InstagramService>

@{

    InstagramSearchTagsResponse response = Model.Tags.Search("bacon");
    
    <h3>Tags matching search (@response.Body.Data.Length)</h3>
    
    foreach (InstagramTag tag in response.Body.Data) {
        
        <div>@tag.Name (@tag.MediaCount)</div>
        
    }
    
}
```

I will make a new release in one of the following days (or today if I can make it).
