### ISSUE TITLE
Possible to change API version?

### ISSUE THREAD

**Issue by seanhak** [abjerner/Skybrud.Social#38]
This 2.4 "optimization" from Facebook really bums me out since GetPosts doesn't support fields yet.

However is it possible to specify with some kind of option to use 2.3 until skybrud is 100% compatible? It shouldn't shut down until 2017 something.

Cheers!

**Comment by abjerner** [comment]
Hi Sean,

If you update to `v0.9.4.1` (released last night), this is now supported through the `FacebookGetPostsOptions ` class - I just haven't had the time to update the documentation yet.

```C#
// Declare the options for the call to the API
FacebookGetPostsOptions options = new FacebookGetPostsOptions {
    Identifier = "skybrud",
    Fields = new [] { "id", "name", "from", "message" }
};

// Make the call to the API
FacebookPostsResponse response = service.Posts.GetPosts(options);
```

Regarding using an older version of the Graph API, this is actually also supported. But with a big IF. When you register a new app, the app is automatically configured to use the latest version of the API at the time. You can only use that version or newer, but not older versions. So this is app specific. As far as I know, it is not possible to change this.

So for my test app created years ago, I can still use `v2.0`, whereas another test app I created the other day, is configured to use `v2.4`, and therefore won't let me use earlier versions. As someone developing a package for other developers to use, this is really a frustrating move by Facebook.

You can see which version your app was registered with on the dashboard for your app in the developer section.

![image](https://cloud.githubusercontent.com/assets/3634580/9276935/442456de-42a7-11e5-93db-9f1a1f2abd61.png)

If your app is allowed to use an older version of the API, you can tell Skybrud.Social to use that version like this (where `service` is an instance of `FacebookService`):

```C#
service.Client.Version = "v2.3";
```
 
Hope this solves your problems ;)

**Comment by seanhak** [comment]
Wow, thanks for reply, didn't expect you to reply that fast.
I'm running this update, I think there ***might*** be a bug, I can use `FacebookGetPostOptions` for `GetPost`, but not `GetPosts`, which only accepts `FacebookPostsOptions`.

My mind is a bit blurry right now, but I recall same issue applies to the `GetFeed`.

API versioning is awesome, that is definitely some good practice to always specify just in case Facebook updates API versions during holidays or what not.

**Comment by abjerner** [comment]
It should still work. Notice that for the `GetPost` method the options class is called `FacebookGetPostOptions` with post in singular, while for the `GetPosts` the (new) options class is called `FacebookGetPostsOptions` with posts in plural.

I just created a new and clean console application, installed `v0.9.4.1`of Skybrud.Social, and the following code compiles and works fine:

```C#
using System;
using Skybrud.Social.Facebook;
using Skybrud.Social.Facebook.Options.Posts;
using Skybrud.Social.Facebook.Responses.Posts;

namespace ConsoleApplication1 {
    
    class Program {
        
        static void Main(string[] args) {

            // Initialize a new service instance
            FacebookService service = FacebookService.CreateFromAccessToken("my token");

            // Declare the options for the call to the API
            FacebookGetPostsOptions options = new FacebookGetPostsOptions {
                Identifier = "skybrud",
                Fields = new[] { "id", "name", "from", "message" }
            };

            // Make the call to the API
            FacebookPostsResponse response = service.Posts.GetPosts(options);

            Console.WriteLine(response.Body.Data.Length);
        
        }
    
    }

}
```

**Comment by seanhak** [comment]
Oh I see now, I'm so stupid :facepunch: 
Your example works excellent - no bug! I used `GetPosts("identifier", options)` - that's why I was "only" getting standard `FacebookPostsOptions`

Thanks a lot for *all* your help mate!

**Comment by abjerner** [comment]
No worries. I changed the parameters, and haven't updated the documentation yet ;)
