### ISSUE TITLE
Facebook - how to get a list of posts with specific fields from a feed

### ISSUE THREAD

**Issue by Krustocious** [abjerner/Skybrud.Social#39]
Hi there,
I've been playing around with both the Skybrud.Social Instagram and Facebook API's for a bit, and had a few questions about Facebook. 

I am currently able to get a list of posts (with specified fields) from a Facebook page (i.e all posts the admin of the page had made) with no problems, but I was wondering how I would get a list of posts from the feed of a Facebook page (i.e every post that has been posted to that page, be it from the admin or other users). Looking at the graph API explorer it seems possible, but is there a way to do this with the current Skybrud.Social API?

In addition, I would like to make the list of posts from the feed with the same specific fields as the regular list of posts. Looking through the FacebookFeedOptions, there didn't seem like a way to specify fields in a feed the same way you can with the FacebookGetPostsOptions in a post. I tried modifying the FacebookFeedOptions in the dll to include these options, but I do not know how I would go about adding the response.Body.Data to a list (unsure of which list type to use).

Perhaps I'm going about this all wrong, but here is what I am attempting to do:
(Apologies for syntax, I believe this is my first post)
```C#
FacebookFeedOptions fOptions = new FacebookFeedOptions() {
    Fields = "id,message,from,created_time,object_id,type",
    Limit = 5
}
FacebookFeedResponse response = service.Feed.GetFeed(pageName,fOptions);
```
After modifying the dll, these appear to be fine. I just don't know what type of list I would add the response.Body.Data to.

Sorry for the long post!

**Comment by abjerner** [comment]
Hi Krustocious,

I haven't gotten around to add support for fields to the `GetFeed` method yet. If you just need to get the posts of a Facebook page, you should still be able to get the posts of that page by specifying the alias - eg. like:

```
// Declare the options for the call to the API
FacebookGetPostsOptions options = new FacebookGetPostsOptions {
    Identifier = "skybrud",
    Fields = new [] { "id", "name", "from", "message" }
};

// Make the call to the API
FacebookPostsResponse response = service.Posts.GetPosts(options);
```

If you're still poking around in the source code, you can use the page method as an example. It shouldn't be necessary to update `response.Body.Data`, but merely the arguments that are sent to Graph API (as defined by the `FacebookFeedOptions` class). I will see if I can find the time to update this soon to support fields ;)

**Comment by abjerner** [comment]
I have now made a commit that adds support for fields:

https://github.com/abjerner/Skybrud.Social/commit/e002dea3628448e0a77e50316c80b3b1a46f7eea

There is now a `FacebookGetFeedOptions` class that replaces the old `FacebookFeedOptions` class. The old one is kept for legacy support, but doesn't support fields.

For now, you can only get new class by pulling down the repository, and then building the main project. But I will continue to work on that tomorrow ;)

**Comment by Krustocious** [comment]
Hi Anders,
Thank you for adding the feed support! I'm still not able to make a list of facebook posts from the feed of a page however. I was looking for the `response.Body.Data` so I could make a list with it (for pagination etc.), but a feed is more of an entire block of data than the individual posts. Would there be some way to convert a feed of a page into a list of posts?

**Comment by abjerner** [comment]
If you just need to get the posts of a page, you should be able to use my example from before. From what I have experienced with the Graph API so far, I can't see why that wouldn't work.

If it however still doesn't work, I'm more likely to think this is an issue with the Graph API itself, but if you can post some more information about your code, I can have another look at it ;)

**Comment by Krustocious** [comment]
Hi Anders,

I can get the posts of a page just fine, but I'm looking to get the feed posts (posts to the page from both the admin and other users) and add them to a **list**. I can get the feed as a block of data, but I'm not sure how to break it up into a list as I am able to do with the `FacebookGetPosts response`. I'm essentially looking to take the data from 
`https://graph.facebook.com/(page)/feed?fields=id,created_time,message,object_id,from&access_token=(access token)` and add each post from the feed to a list.

Sorry if there has been any confusion.

**Comment by abjerner** [comment]
Hi again,

I'm not exactly sure what you're trying to accomplish. Given the feed URL that you posted, a similar call with Skybrud.Social would look like (if you use the latest code from the repository):

```C#
@using Skybrud.Social.Facebook.Objects.Feed
@using Skybrud.Social.Facebook.Options.Feed
@using Skybrud.Social.Facebook.Responses.Feed
@inherits System.Web.Mvc.WebViewPage<Skybrud.Social.Facebook.FacebookService>

@{

    FacebookFeedResponse response = Model.Feed.GetFeed(new FacebookGetFeedOptions {
        Identifier = "(page)",
        Fields = "id,created_time,message,object_id,from"
    });
    
    foreach (FacebookFeedEntry item in response.Body.Data) {
        
        <p>@item.From.Name: @item.Message</p>
        
    }
    
}
```

**Comment by abjerner** [comment]
Hi Krustocious,

Did you find a solution to your problem? In my last example, `response.Body.Data` is simply an array holding instances of `FacebookFeedEntry`.

I'm not sure what you mean by a list, but you can simply call `response.Body.Data.ToList()` using LINQ to convert the array into a list, or add the array to an already existing list like:

```C#
List<FacebookFeedEntry> list = new List<FacebookFeedEntry>();

list.AddRange(response.Body.Data);
```

**Comment by Krustocious** [comment]
Hi Anders, 

I've been working on some other things, sorry for the late reply. I had a shot with what you posted, but I'm just using plain c# without asp.net, and I can't seem to be able to detect the .Mvc section of the inherits line (although mine looked more like `class Facebook :` instead of `inherits`. Is there a way to inherit the FacebookService WebViewPage another way?

**Comment by abjerner** [comment]
Sorry for not getting back to you sooner. The MVC inherits statement simply means that my view will inherit from the `System.Web.Mvc.WebViewPage` class, and have a model of the type `Skybrud.Social.Facebook.FacebookService`.

For the code to work, you really just need to have an instance of `Skybrud.Social.Facebook.FacebookService`. The MVC part is part of the example, but not really needed.

Since this issue is now a few months old, I'm closing it for now. But if you need my help, simply feel free to open the issue again, and I'll have another look ;)

**Comment by Brighty28** [comment]
Can you advise how I get story attachments for example:
![capture](https://cloud.githubusercontent.com/assets/6204366/25803032/0659b8b0-33ed-11e7-8362-37255809e696.PNG)

These are the fields I have so far
```
 FacebookGetPostsOptions options = new FacebookGetPostsOptions
        {
            Identifier = "FitCubs",
            fields=cover,name,likes,link,posts.limit(50){created_time,message,link,type,full_picture,picture,source,icon}&access_token=" + appId + "|" + appSecret;
            Fields = "attachments,cover,name,likes,link,posts,created_time,message,type,full_picture,picture,source,caption,media,url"
    	};
```
