### ISSUE TITLE
Dropbox support

### ISSUE THREAD

**Issue by bjarnef** [abjerner/Skybrud.Social#45]
Hi Anders

I thought about if it would make sense to include support for Dropbox? https://www.dropbox.com/developers-v1/core/docs#oa2-authorize

Maybe also similar data storage services like box.net, drive.google.com, onedrive.com ... ?

**Comment by abjerner** [comment]
Hi Bjarne,

I think that I already have some code for Dropbox somewhere, but can't remember why it isn't part of the package. I'll look into that ;)

Are you just looking for the authentication part, or also the mapping of the APIs as well? For Google Drive, you should be able to use the existing Google code for the authentication part. I haven't worked with Box.com before, but I'll that to the todolist as well.

**Comment by bjarnef** [comment]
I have seen different "dropbox" JavaScript/AngularJS filepickers, where you might want to use it - on frontend, in a restricted area or maybe in Umbraco backoffice? I thought about it could be cool if you could upload files in Umbraco media section by picking files from Dropbox (so the authentication part - but maybe some of the other APIs would be useful too. Btw. does Skybrud.Social include Flickr? (just thought about nuPickers)

Okay, so I guess the Microsoft authentication part would work with onedrive.com?

I having a specific case about these stuff at the moment, I just thought about it and it could be useful :)

I would be pretty cool if there was a package for media section in Umbraco, which allowed you to pick files from external data sources like Dropbox, OneDrive, Google Drive, Flickr etc., but maybe in that case it should be a separate package and not depend on Skybrud.Social is installed. Maybe just re-use part of Skybrud.Social that is needed. I thought about all of this, because I saw this package :package: 
https://our.umbraco.org/projects/backoffice-extensions/zippy-media-import/

**Comment by bjarnef** [comment]
An example file picker with Dropbox and Box.net :)
https://github.com/geojacobm6/angular-dropbox-box-picker

**Comment by abjerner** [comment]
The services you're mentioning are all on my own "nice to have" list, so I'll look into them when I have the time.

Flickr isn't supported at the moment, but it is also something I have thought about adding. Our own CMS Skybrud.edit has support for Flickr, so there might be some code here that can be reused ;)

I haven't really looked into OneDrive yet, but I assume the Microsoft authentication should work fine if you look up the correct scopes somewhere in their documentation.

I have had similar thoughts regarding a file picker for Umbraco, but haven't gotten around to it yet. My original plan with [Skybrud.Social for Umbraco](https://github.com/abjerner/Skybrud.Social.Umbraco) was to create a *uComponents for social sevices* (big steps to fill) beyond the property editors currently in my package. But that is also something that takes a lot of time. A file picker could therefore me made as it's own package. I'll look a bit more into that when I have the time ;)

**Comment by abjerner** [comment]
OneDrive has possible values for the scope, so I have now implemented them here: https://github.com/abjerner/Skybrud.Social/commit/9012bec4a3e567243e15675f211e7ed2ac1b26ab

If you clone the repository and build the Skybrud.Social.Microsoft project, you can now do something like:

```C#
 // Construct the authorization URL
string url = client.GetAuthorizationUrl(state, WindowsLiveScopes.Emails + WindowsLiveScopes.Birthday + OneDriveScopes.Readonly);
```

**Comment by bjarnef** [comment]
Okay cool :) .. it would be nice with these additional services, but it's not urgent though..
However I think OneDrive has become more popular the recent years since they offer more free storage as default compared to e.g. Dropbox.

I also thought about some file pickers for external data storage services in the cloud .. I have noticed  Dropbox Selector https://our.umbraco.org/projects/backoffice-extensions/dropbox-selector/ which use Dropbox chooser, but also the old Universal Media Picker https://our.umbraco.org/projects/backoffice-extensions/universal-media-picker/ ...

It like the idea with Universal Media Picker of having different providers foreach service making it extensible.. 
Actually there exists a service like Filepicker www.filepicker.com (this project seems to use it in AngularJS https://github.com/filepicker/filepicker-angular) but I would prefer an open source solution .. maybe a combination of Universal Media Picker and what filepicker.com offer.. and as a start I think it would be just fine with some of the most popular services..
Of course it will take time, but I think it is worth discussing it :)

It might be an options to use the "filepickers" from OneDrive, Dropbox, Box.net like in this project https://github.com/geojacobm6/angular-dropbox-box-picker .. or maybe the same can be done through the API (I guess those filepickers are more easy-to-use widgets).

Great.. I might have some time later in the week to play with it :)

**Comment by abjerner** [comment]
Still very limited, a project for the Dropbox implementation (mostly authentication and hardly any API mapping) is now available here: https://github.com/abjerner/Skybrud.Social.Dropbox

I'll close the issue here since Dropbox now lives in it's own repository ;)

In addition to Dropbox, you can now also find a repository for Box:

https://github.com/abjerner/Skybrud.Social.Box

Authentication with OneDrive is now also possible due to the scopes I've added to the Microsoft implementation:

https://github.com/abjerner/Skybrud.Social.Microsoft/blob/master/src/Skybrud.Social.Microsoft/OneDrive/Scopes/OneDriveScopes.cs

Again, this is currently very limited, but I'll look further into all three projects soon ;)
