### ISSUE TITLE
Facebook - How to get a list of friends

### ISSUE THREAD

**Issue by inovacode** [abjerner/Skybrud.Social#50]
Skybrud Social has been a great tool for my project.  However, it looks like it's missing support for the me/friends Facebook endpoint.  https://developers.facebook.com/docs/graph-api/reference/v2.5/user/friends

Is it there somewhere and I'm not seeing it?  If not, is there a way I can use Skybrud.Social to make that API call to return a dynamic object I can parse manually?

Thanks for your help!

**Comment by abjerner** [comment]
Hi James,

The friends endpoint method is a bit limited in the way that in will only list friends that are also using the app used for making the calls. You won't be able to get a full list of your friends, and as a result of this, I haven't really focused on adding support for the endpoint method yet.

Anyways, you can still come a long way with some of the logic used internally in Skybrud.Social. With this small Razor example, you can fetch a list of your friends.

```C#
@using System
@using Skybrud.Social.Facebook
@using Skybrud.Social.Facebook.Objects.Users
@using Skybrud.Social.Http
@using Skybrud.Social.Json

@{

    // Initialize a new service instance
    FacebookService service = FacebookService.CreateFromAccessToken(accessToken);

    // Make a call to the API to get the raw response (this is what Skybrud.Social normally does under the hood)
    SocialHttpResponse response = service.Client.DoAuthenticatedGetRequest("/me/friends?fields=id,name,bio,cover");

    // Parse the response body into an instance of "JsonObject"
    JsonObject obj = JsonObject.ParseJson(response.Body);
    
    // Iterate through the "data" array
    foreach (FacebookUser friend in obj.GetArray("data", FacebookUser.Parse)) {

        <h1>@friend.Name (@friend.Id)</h1>

        // Print the bio (if specified)
        if (!String.IsNullOrWhiteSpace(friend.Bio)) { <p>@friend.Bio</p> }

        // Print the cover (if specified)
        if (friend.Cover != null) { <p><img src="@friend.Cover.Source" /></p> }

        // Print out the JSON (eg. for debugging)
        <pre>@friend.ToJson()</pre>

    }
    
}
```

I you need more fields that the ones returned, you can simply append the fields to the URL being requested. `<pre>@friend.ToJson()</pre>` will print the JSON for each friend so you can see what is actually returned by the API.

**Comment by inovacode** [comment]
Exactly what I needed.  Thanks!!
