### ISSUE TITLE
Getting 'Value was either too large or too small for an Int32' Instagram

### ISSUE THREAD

**Issue by khraibani** [abjerner/Skybrud.Social#52]
I have attached a screengrab of the error. any idea of how to fix it?

![instag](https://cloud.githubusercontent.com/assets/4085627/15184315/a62733fa-178c-11e6-9511-ee31289b78e5.JPG)

**Comment by abjerner** [comment]
Yes, actually. The newest release (from earlier today) contains a fix for this ;)

https://github.com/abjerner/Skybrud.Social/releases/tag/v0.9.4.2

**Comment by khraibani** [comment]
Brill! Thanks for the quick response. When would that be fixed for the umbraco package. "Skybrud.Social.Umbraco"

**Comment by abjerner** [comment]
If you have installed `Skybrud.Social.Umbraco` via NuGet, you can simply update the `Skybrud.Social` dependency to the new version. Otherwise, replacing `Skybrud.Social.dll` in your bin folder with the new release should do it as well ;)

**Comment by khraibani** [comment]
Brill thanks you for your help!
