### ISSUE TITLE
YouTube Videos

### ISSUE THREAD

**Issue by deepa201** [abjerner/Skybrud.Social#53]
Hi, 

I am trying to get the latest 5 videos of youtube for the user. I have the serverkey, browser key, userid. I would like to have a sample code for authenticating the google service using your library. I have a service with the methods for facebook,twitter, instagram and youtube. i was able to do it successfully for the other three social media using your library. 

Also how do i get the latest videos published by the user.

Any help would be appreciated.

Code that i have for youtube service
 GoogleService googleService = GoogleService.CreateFromServerKey(youTubeApiServerKey);
   YouTubePlaylistListOptions playListOptions = new YouTubePlaylistListOptions()
            {
                Part = new YouTubePlaylistPartsCollection("snippet"),
                Mine = true
            };

            YouTubePlaylistListResponse playListResponse = googleService.YouTube.Playlists.GetPlaylists(playListOptions);

            //// Iterate through the playlist items
            foreach (YouTubePlaylist playListItem in playListResponse.Body.Items)
            {

                YouTubePlaylistItemListOptions options = new YouTubePlaylistItemListOptions()
                {
                    Part = new YouTubePlaylistItemPartsCollection("contentDetails", "snippet"),
                    PlaylistId = playListItem.Id

                };

                YouTubePlaylistItemListResponse response = googleService.YouTube.PlaylistItems.GetPlaylistItems(options);
                    //Playlists.GetPlaylists(options);

                //// Iterate through the playlist items
                foreach (YouTubePlaylistItem item in response.Body.Items)
                {
                    // Do something with the post  
                    SocialWallModel socialWallModel = new SocialWallModel();

                    if (item.Snippet != null)
                    {
                        socialWallModel.Title = item.Snippet.Title;
                        socialWallModel.Text = item.Snippet.Description;
                        socialWallModel.Date = item.Snippet.PublishedAt;
                    }

                    socialWallModel.ThumbURL = string.Format("https://www.youtube.com/watch?v={0}", item.Id);
                    socialWallModel.SocialFeedtype = SocialType.YouTube;
                    socialWallModel.Icon = icon;
                    socialWallModel.Link = string.Format("https://www.youtube.com/watch?v={0}", item.Id);
                    socialWallModelList.Add(socialWallModel);

                }
            }

Thanks,
Deepa

**Comment by abjerner** [comment]
@deepa201 A server key doesn't give a user context, so it won't know about your user. With your current code, you should use an access token (or refresh token) instead, which gives you a user context.

Alternatively you can request items of a given channel instead:

```C#
YouTubePlaylistListOptions playListOptions = new YouTubePlaylistListOptions()
{
Part = new YouTubePlaylistPartsCollection("snippet"),
ChannelId = "id of the user channel"
};
```

**Comment by deepa201** [comment]
I have the client id and client secret key, which method do i use for creating access token or refresh token. 

Even if i give user channel info, how do i get the latest videos published?

**Comment by deepa201** [comment]
Got it working, Used the username in Get Channel methods and drilled down till i get playlistitems. 

ThANKS

**Comment by abjerner** [comment]
I haven't had time to answer before now, so good to see you found a solution :+1:
