### ISSUE TITLE
source code zip file issue

### ISSUE THREAD

**Issue by deepa201** [abjerner/Skybrud.Social#54]
Hi,

I took the zip file, extracted all the files and included in my solution

Below is the error i am getting while building the project Skybrud.Social.Core
Also,If i want to include any of the services like facebook.. i have to include those projects in my solution and refer those dlls in my project right?

Error	9	The command ""C:\Workspace\Skybrud.Social.PreBuildTool.exe" 2012-07-30 "C:\Workspace\ExternalModules\Skybrud.Social-master\src\Skybrud.Social.Core\Skybrud.Social.Core.csproj"

copy C:\Workspace\ExternalModules\Skybrud.Social-master\src\Skybrud.Social.Core\Properties\AssemblyInfoGenerated.cs C:\Workspace\Skybrud.Social\Properties\AssemblyInfoVersion.cs
copy C:\Workspace\ExternalModules\Skybrud.Social-master\src\Skybrud.Social.Core\Properties\AssemblyInfoVersion.cs C:\Workspace\Skybrud.Social\Properties\AssemblyInfoVersion.cs" exited with code 1.	Skybrud.Social.Core (ExternalModules\Skybrud.Social\Skybrud.Social-master\src\Skybrud.Social.Core\Skybrud.Social.Core)

**Comment by abjerner** [comment]
Have you by any chance moved some of the files around? I just tried downloading the ZIP, starting up the Visual Studio solution, and building worked fine.

In your case, the build events have tried to execute `C:\Workspace\Skybrud.Social.PreBuildTool.exe`, but based on the rest of the error message, it really should try to execute `C:\Workspace\ExternalModules\Skybrud.Social-master\src\Skybrud.Social.PreBuildTool.exe`. It works fine on the machines I have tested on so far, so I can't think any reasons why it doesn't work in your case. Anyways, the build events are mostly something I use internally. If you're working on your own build, you can simply disable/remove all build events.

Regarding what projects to include really depends on what you're trying to do. May I ask why you're downloading the source code rather that just using the NuGet package(s)?

**Comment by abjerner** [comment]
@deepa201 I haven't heard back from you, so I'm closing this issue. Feel free to post another comment of you're still having issues ;)
