### ISSUE TITLE
The Instagram API no longer support making requests using just the client_id.

### ISSUE THREAD

**Issue by mrflo** [abjerner/Skybrud.Social#55]
Hi Anders,

Thanks again for the useful tools you have shared! 
I am experiancing issue with Instagram. They are not allowing a request with the client id:
"The Instagram API requires an access_token from authenticated users for each endpoint. We no longer support making requests using just the client_id."

So different methods are not working anymore including the one to get the feed.

Do you know if there is a way to get a public feed server side ?

**Comment by abjerner** [comment]
Hi Florent,

Yes, unfortunately Instagram has removed the support for using just a client ID. So now you'll need to obtain an access token. In order to obtain an access token, you'll need to setup an authentication page, which requires some extra work, but is a one-time thing. You can use my file for inspiration:

https://github.com/abjerner/Skybrud.Social.Umbraco/blob/master/src/Skybrud.Social.Umbraco/App_Plugins/Skybrud.Social/Dialogs/InstagramOAuth.aspx.cs

If you setup the authentication page, you can log in with your own Instagram account, and then save the obtained access token for later use.

I hope this answers your question ;)

**Comment by mrflo** [comment]
Thanks for your quick answer.
Isn't a possibility to do it server side like suggested in this post ? 
http://stackoverflow.com/questions/34299125/call-instagram-api-without-access-token

**Comment by abjerner** [comment]
@mrflo If you see the first answer, he explains two methods for obtaining an access token.

The first method is called explicit authentication, which more or less is the same as shown in the file I referenced in my last comment. This will require you to log in with your own account, but keep in mind that you only have to do this once.

The second method is called implicit authentication. Last year Instagram made some changes to their authentication, which means this method is no longer supported.

**Comment by mrflo** [comment]
@abjerner Thanks, it wasn't clear for me if I still needed to input my login detials but now It's working except that I am using your Instagram endpoint to get the user feed but it's pointing to   
```
public SocialHttpResponse GetUserFeed(InstagramGetUserFeedOptions options) {
            if (options == null) throw new ArgumentNullException("options");
            return Client.DoHttpGetRequest("https://api.instagram.com/v1/users/self/feed", options);
 }
```
And apparently it should point to "https://api.instagram.com/v1/users/self/" now:

https://www.instagram.com/developer/endpoints/users/#get_users_self

**Comment by abjerner** [comment]
@mrflo I think I vaguely remember reading something about Instagram has dropped support for the feed endpoint as well.

The feed endpoint would return a list of media similar to when you go to https://www.instagram.com/ in your browser, whereas the https://api.instagram.com/v1/users/self/ endpoint will return information about the authenticated user. So I'm afraid there's not much I can do here :(

Anyways, just to be sure: if you want to retrieve a list of the most recent media of the authenticated user, you should use the https://api.instagram.com/v1/users/self/media/recent/ endpoint (or the `GetRecentMedia` method in my code).
