### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by cbrown1334** [abjerner/Skybrud.Social#61]
Anders:

Occasionally, the calls to "GetUserTimeline" (Twitter), "GetPosts" (Facebook), or "GetRecentMedia" (Instagram) will fail with "The request was aborted: Could not create SSL/TLS secure channel".  It seems kind-of random, but thought I'd check and see if you've seen this before.  Works fine most of the time.

I have seen this error before when calling into the UPS webservice or Stamps.com.  If I remember correctly, I had to change "SecurityProtocolType" from Ssl3 to Tls12.  I search through your code for "Security Protocol" and didn't get a hit - so maybe I'm way off.  And in that case it stopped working altogether. 

I could certainly put the calls in a Try/Catch block and just abort if it gets the error (which the production code will have anyway).  Would be nice to figure it out, though, and make sure I'm not screwing something up.

Environment:  My development machine is Windows 10 with Visual Studio Community 2015.  The website is ASP.Net 4.5.2.  This is all web forms stuff.

Background:  Using Skybrud.Social to scrape Facebook, Twitter, and Instagram posts for display on our website.  Works great and has saved a bunch of time (over the old code that used each site's proprietary API's).  My code builds an XML file from the data pulled from social media.  When a user hits my page it checks how long it's been since the file was updated and spins off a thread to refresh the file if it's aging is more than a certain time period.  That way every user doesn't have to make the call to get the posts.  The webpage is built off of the contents of the XML file.

I suppose it is possible that the different services could be getting called at the same time as each other.  Maybe your code isn't thread safe?  Maybe the different services are bumping into each other?  Any thoughts?  Thanks!

Chris

**Comment by abjerner** [comment]
I haven't really experienced any issues yet in multi threaded environments - but it's not something I have tested against specifically. I also haven't seen that exception in Skybrud.Social before.

After Googling a bit, the primary cause of the `The request was aborted: Could not create SSL/TLS secure channel` exception seems to be when there's something wrong with the certificate on the server. Based on the fix that you describe you have used in the past, I think this was the cause there.

However the fact that you're experiencing the exception with both Twitter, Facebook and Instagram, and this only happens momentarily, I think it's something else that goes wrong, although the exception message is the same.

Internally Skybrud.Social uses the `WebRequest` and `HttpWebRequest` classes for making HTTP(s) requests - I'm not really doing anything else to handle HTTPS requests. I can't really think of anything in Skybrud.Social that would cause this error (although I'm not ruling it out). So based on past error reports, I think it's more likely to be an issue in your local environment.

To rule things out, do you see the same exception in other environments and/or networks? Could you perhaps share some of your code (then I can try to recreate it at my end)?

Regarding your use of threads, I tried setting up a simple example in a Razor view, but everything here works fine:

```C#
@using System.Threading
@using Skybrud.Social.Facebook
@using Skybrud.Social.Instagram
@{

    FacebookService facebook = FacebookService.CreateFromAccessToken("");
    InstagramService instagram = InstagramService.CreateFromAccessToken("");

    string pathFacebook = Server.MapPath("~/App_Data/Facebook.json");
    string pathInstagram = Server.MapPath("~/App_Data/Instagram.json");

    if (true || !File.Exists(pathFacebook)) {

        FacebookThread fb = new FacebookThread(facebook, pathFacebook);

        // Create the thread object, passing in the Alpha.Beta method
        // via a ThreadStart delegate. This does not start the thread.
        Thread thread = new Thread(new ThreadStart(fb.Beta));

        // Start the thread
        thread.Start();

    }

    if (true || !File.Exists(pathInstagram)) {

        InstagramThread ig = new InstagramThread(instagram, pathInstagram);

        // Create the thread object, passing in the Alpha.Beta method
        // via a ThreadStart delegate. This does not start the thread.
        Thread thread = new Thread(new ThreadStart(ig.Beta));

        // Start the thread
        thread.Start();

    }
    
}

@functions {

    public class FacebookThread {

        public FacebookService Service { get; private set; }

        public string Path { get; private set; }

        public FacebookThread(FacebookService service, string path) {
            Service = service;
            Path = path;
        }

        public void Beta() {

            Service.Posts.GetPosts("skybrud").Body.JsonObject.SaveJson(Path);
            
        }
    
    }

    public class InstagramThread {

        public InstagramService Service { get; private set; }

        public string Path { get; private set; }

        public InstagramThread(InstagramService service, string path) {
            Service = service;
            Path = path;
        }

        public void Beta() {

            Service.Users.GetRecentMedia().Body.JsonObject.SaveJson(Path);

        }

    }

}
```
