### ISSUE TITLE
How to use `AnalyticsDimension.DimensionXX`?

### ISSUE THREAD

**Issue by leekelleher** [abjerner/Skybrud.Social#62]
> I'm using Skybrud.Social v0.9.4.6 (with the Umbraco package)

With the Google Analytics Data API, are we able to query for custom dimensions?
I'm not sure how the `AnalyticsDimension.DimensionXX` property should work.

Is it possible to create custom `AnalyticsDimension` objects for them,
e.g. `new AnalyticsDimension("ga:dimension1")`?

(I tried looking at the source-code, but it appears the constructor is marked as private.)

Thanks, Lee.

**Comment by abjerner** [comment]
@leekelleher As far as I remember, there is some operator overloading that let's you write something like `AnalyticsDimension dimension = "ga:dimension1";`.

If that doesn't work, please write back, and I'll have a look at it when I get home ;)

**Comment by leekelleher** [comment]
Thanks @abjerner - I got quite excited then 😃 

Unfortunately it threw an error...

    System.Exception: Invalid dimension 'ga:dimension1'

_sorry to say_ 😢

**Comment by leekelleher** [comment]
Digging through the source, it looks like it falls over at the `TryParse` when looking up the `Values`.

**Comment by abjerner** [comment]
From `v1`, each service will be separated into it's own package. I can see that I in *Skybrud.Social.Google` (which is still in beta) have made the constructor public:

https://github.com/abjerner/Skybrud.Social.Google/blob/master/src/Skybrud.Social.Google/Analytics/Dimensions/AnalyticsDimension.cs#L56

It will look into bringing some of that back to `v0.9.x` ;)

**Comment by leekelleher** [comment]
@abjerner I'm happy to send over a PR for this, if that helps?

**Comment by abjerner** [comment]
@leekelleher A pull request never hurts ;) But in this case, it took longer to push the actual release than to change the visibility of the constructors:

https://github.com/abjerner/Skybrud.Social/releases/tag/v0.9.4.7

**Comment by leekelleher** [comment]
Thanks @abjerner! #h5yr

I've gotta say, I've used this library in the past but never fully realised how fully featured it was... you've done an amazing job! 😎
