### ISSUE TITLE
What is the target for this library?

### ISSUE THREAD

**Issue by assassin316** [abjerner/Skybrud.Social#67]
Can someone tell me the target platform for this library? I tried adding the nuget package to a PCL, a UWP class library, a .Net Core library, and a Xamarin PCL, but none work.

**Comment by abjerner** [comment]
Skybrud.Social targets the full .NET framework. The `Skybrud.Social` NuGet package targets `v4.0`, while the `Skybrud.Social.Core` NuGet package targets `v4.5`.

I don't really have any experience with targeting portable platforms - or .NET core for that matter - so these platforms are not supported.
