### ISSUE TITLE
FacebookOAuthClient.GetAccessTokenFromAuthCode returns null

### ISSUE THREAD

**Issue by azzimuth** [abjerner/Skybrud.Social#68]
My Facebook integration stopped working and once I debug I see that the `FacebookOAuthClient.GetAccessTokenFromAuthCode` stopped returning valid access token and returns instead `null`. Are there any breaking changes in Facebook's API which could cause this? As I said, this was working flawlessly until now.

**Comment by azzimuth** [comment]
Posted an issue in Facebook repository.

**Comment by ZacP** [comment]
@azzimuth Did you find anything on this?  We've encountered the same issue

**Comment by ZacP** [comment]
Note: resolved here: https://github.com/abjerner/Skybrud.Social.Facebook/issues/18

**Comment by abjerner** [comment]
@ZacP Seems you already have found the answer. Anyways, the Facebook authentication issue was fixed in this release: https://github.com/abjerner/Skybrud.Social/releases/tag/v0.9.5
