### ISSUE TITLE
Posting images to Instagram

### ISSUE THREAD

**Issue by famous1234** [abjerner/Skybrud.Social#70]
I have authorized the user and got the access token and I'm stuck. I cant any reference regarding posting images and status to instagram. The Instasharp package doesnot work in asp.net core. So AnyBody Out There to help me???

**Comment by abjerner** [comment]
The Instagram API - as far as I know - doesn't support uploading images. This must be done through the Instagram app on your phone.

Skybrud.Social is build against the full .NET framework, and as such doesn't support ASP.NET Core either.
