### ISSUE TITLE
Facebook not returning anything other than id and message for posts

### ISSUE THREAD

**Issue by joshua-stewart** [abjerner/Skybrud.Social#73]
Just noticed that when using Skybrud.Social 0.9.6 all of the posts returned from Facebook have null for almost everything except date fields and the post id and message. Is anyone else seeing this?

**Comment by abjerner** [comment]
@joshua-stewart Facebook only returns a few fields by default, which is why most properties are either null or empty. You can specify which fields should be returned by the API - this is explained a bit more here:

http://social.skybrud.dk/facebook/fields/

Hope that helps ;)

**Comment by joshua-stewart** [comment]
We didn't change anything though. It had been working without any issues until just recently (I noticed today) but when we deployed the update to 0.9.6 at the end of May everything worked.

**Comment by joshua-stewart** [comment]
We are using `FacebookPostsCollection response = facebook_service.Posts.GetPosts(facebook_account, 20).Body;`
How would I pass options with this call?

**Comment by abjerner** [comment]
@joshua-stewart When you register a new Facebook app, it is automatically configured to use the latest version at that time. You can explicitly choose to use a newer version, but not an older version.

My bet is that your app was created a while a go, and as such was configured to use `v2.3` or an older version of the Facebook Graph API, which would return more fields by default.

However Facebook are continuously deprecating old versions of their API, where each version is supported for at least two years. When an old version is deprecated, your app is automatically bumped up to the lowest supported version, which would probably be `v2.4` in your case (`v2.3` was deprecated the 25th of March this year). As of `v2.4`, the Graph API will return fewer fields by default as described on the page I linked to before.

There is a bit more information about the versioning here: http://social.skybrud.dk/facebook/version/

**Comment by abjerner** [comment]
@joshua-stewart Instead of just specifying the identifier as the first parameter, you can instead specify an instance of `FacebookGetPostsOptions`, which gives you a few extra options - eg. the `Fields` property. With this class, your code could be updated to look something like:

```C#
@using Skybrud.Social.Facebook
@using Skybrud.Social.Facebook.Objects.Posts
@using Skybrud.Social.Facebook.Options.Posts
@using Skybrud.Social.Facebook.Responses.Posts
@inherits WebViewPage<FacebookService>

@{
    
    // Initialize the options for the call to the API
    FacebookGetPostsOptions options = new FacebookGetPostsOptions {
        Identifier = "skybrud",
        Fields = "name,likes,link,created_time,message,type,full_picture,picture,source,caption",
        Limit = 20
    };

    // Make the call to the Facebook Graph API
    FacebookPostsResponse response = Model.Posts.GetPosts(options);


    // Iterate over the posts
    foreach (FacebookPost post in response.Body.Data) {
        <pre>@post.Message</pre>
    }

}
```

**Comment by joshua-stewart** [comment]
Fantastic! Thank you so much. That fixed it. Have a great day!

**Comment by abjerner** [comment]
Glad I could help ;)

Anyways, it might not be super clear how this impacts your app as well as Skybrud.Social, but Facebook actually tries to warn about forthcoming changes. Eg. for my test app, I have received the following alerts:

![image](https://user-images.githubusercontent.com/3634580/28378901-23db53b4-6cb2-11e7-957d-ada321a73aa7.png)

As far as I remember, you should also receive notifications for these alerts when you're logged in to the regular Facebook website.
