### ISSUE TITLE
MicrosoftAccessToken excedes maximum length.

### ISSUE THREAD

**Issue by jrnsr8500** [abjerner/Skybrud.Social#74]
I get the following message in the log when trying to authenticate with Microsoft:

Validation failed for one or more entities. See 'EntityValidationErrors' property for more details. The validation errors are: The field MicrosoftAccessToken must be a string or array type with a maximum length of '450'.
--

I understand this functionality is still experimental, but there is little to no documentation so it's hard to troubleshoot.

**Comment by abjerner** [comment]
@jrnsr8500 I haven't really worked on the Microsoft package for a while, but I'll try to check whether something has changed in the API ;)

**Comment by abjerner** [comment]
@jrnsr8500 What does your code look like?

The Microsoft package actually has it's own repository, where the readme has information about setting up an authentication page:

https://github.com/abjerner/Skybrud.Social.Microsoft

I just tried setting up a new MVC project, install the `Skybrud.Social.Microsoft` via NuGet, and then setup an MVC action/view with the code from the readme file, and everything works fine (besides that the examples mention a class called `WindowsLiveUserResponse`, which really should be `WindowsLiveGetUserResponse`).

I can see Microsoft has made some changes to the pages for managing your apps, but it still works when registering a new app:

https://apps.dev.microsoft.com/
