### ISSUE TITLE
skybrud social is not compatible with netcoreapp1.1

### ISSUE THREAD

**Issue by pghdeveloper** [abjerner/Skybrud.Social#79]
Will it be compatible with .netcoreapp in the future?

**Comment by abjerner** [comment]
@pghdeveloper I don't use .NET core myself, so this is currently not a priority.  I do however hope to add support for .NET core at some point, but can't really say when this will be.

**Comment by abjerner** [comment]
@pghdeveloper I've figured out an easy way to support multiple target frameworks within the same Visual Studio project, and also researched a bit on .NET Core and .NET Standard.

As a result of this, a number of the individual Skybrud.Social packages now support .NET Standard 1.3 (and thereby also .NET Core). You can see a list of the packages here:

https://github.com/abjerner/Skybrud.Social/blob/master/README.md#services

The remaining packages will soon be updated to support .NET Standard 1.3 as well ;)

**Comment by pghdeveloper** [comment]
@abjerner, thank you for looking into this.  I will look at this and give you feedback.
