### ISSUE TITLE
Deprecation of Instagram API to make way for the Graph API

### ISSUE THREAD

**Issue by rosannafong** [abjerner/Skybrud.Social#80]
Hi,

I read that the Instagram API will be deprecated from July 2018, to make way for the new Instagram Graph API. Could you please let me know on the following?
- How will this framework be affected?
- Will this framework continue to work after this date?
- Will there be plans to update this framework to use the new Graph API features?

Looking forward to hearing back. Thanks in advanced.

**Comment by abjerner** [comment]
Hi Rosanna,

From what I can tell, the new Graph API will only have a subset of features available in the Platform API today. Unfortunately I can't do much about that part :(

Anyways, if we look at this package specifically (`Skybrud.Social` that is), it will not be updated to work with the new Graph API. I've stopped active development of this package, and I will only update the code base for the occasional bugfix.

The reason for the above is that the Instagram logic has been separated into it's own package called [Skybrud.Social.Instagram](https://github.com/abjerner/Skybrud.Social.Instagram). This will be the package to use going forward, and I plan on adding support for the Graph API here. The package is however currently in beta, but there should be a stable release soon ;)

The existing logic for the Instagram Platform API (in both packages) will stop working as Instagram start to close down this API. Not all features will be removed in July though - you can read more about that here:

https://developers.facebook.com/blog/post/2018/01/30/instagram-graph-api-updates/

Again, there's not much I can do here as both packages relies on the Platform API.

I hope that I've answered your questions ;)
