### ISSUE TITLE
Facebook Images

### ISSUE THREAD

**Issue by Muttzzi** [abjerner/Skybrud.Social#81]
Hello everyone, first of all im kinda new to api world, so thats why this question might sound stupid or newby, Im trying to display facebook posts on my website, like message, time etc... but i cant display images, not sure if skybrud dosent support this feature yet, anyway my code looks like this

var appId = ConfigurationManager.AppSettings["FacebookKey"];
            var fbKeyAcc = ConfigurationManager.AppSettings["FaceBookAccessKey"];
            FacebookOAuthClient client = new FacebookOAuthClient(appId, fbKeyAcc);
            FacebookGetPostsOptions fboptions = new FacebookGetPostsOptions
            {
                Identifier = "fb_name",
                Fields = "name,likes,created_time,message,type,full_picture,picture",
                Limit = 20,
            };
            string accessToken = client.GetAppAccessToken();
            FacebookService serviceFB = FacebookService.CreateFromAccessToken(accessToken);
            FacebookPostsResponse responseFB = serviceFB.Posts.GetPosts(fboptions);
---- ANd here im looping through posts:
 var fbTemps = ((from FacebookPost media in responseFB.Body.Data
                            select new NewsViewModel
                            {
                                FaceBookText = media.Message,
                                DateAdded = media.CreatedTime,
                                FacebookDateTimeAdded = media.CreatedTime,
                                FacebookStory = media.Story,
                                FacebookId = media.Id
                            }).ToList());
i got only few options to choose when writing media. and there is no images to select could anyone help  me with this ? thanks /Patryk

**Comment by FDBenevides** [comment]
Hi @Muttzzi,

1. which version of this framework are you using? 
"As of v1.0, this repository and the corresponding package (Skybrud.Social.Core) will just contain the core functionality, and not the implementation for the individual services. Each supported service will now have it's own repository and package. You can find a list of supported services further down this page."

2. no matter what version you're using, if you're converting the data to a "FacebookPost" model object I think that the full_picture is not yet supported by this framework but the 'picture' is (but @abjerner can confirm that):

check the model object for version 0.9.x: https://github.com/abjerner/Skybrud.Social/blob/v0.9.x/src/Skybrud.Social/Facebook/Objects/Posts/FacebookPost.cs 
check the model object for version 1.x: https://github.com/abjerner/Skybrud.Social.Facebook/blob/master/src/Skybrud.Social.Facebook/Models/Posts/FacebookPost.cs

Although, the Facebook's API has both 'picture' and 'full_picture' as you have stated: https://developers.facebook.com/docs/graph-api/reference/v2.12/post 

3. Use the Facebook's Graph API explorer (https://developers.facebook.com/tools/explorer/145634995501895/ ) to confirm that your AppAccessToken is able to get the posts and also the posts' pictures. Put your AppAccessToken to get the posts, then select a post and use that post-id to do the GET '[post-id]?fields=message,full_picture,picture'

**Comment by abjerner** [comment]
@Muttzzi did you find a solution for your issue? Both packages do support the `Picture` property (equivalent to the `picture` property in the JSON), so you should be able to get that.

Hopefully I can push a new release of `Skybrud.Social.Facebook` tomorrow, which will also support the `full_picture` JSON property ;)

**Comment by abjerner** [comment]
@Muttzzi New release is here https://github.com/abjerner/Skybrud.Social.Facebook/releases/tag/v1.0.0-beta5 ;)
