### ISSUE TITLE
Wich Facebook / Twitter / Instagram API version is supported by this package?

### ISSUE THREAD

**Issue by biapar** [abjerner/Skybrud.Social#84]
Wich Facebook / Twitter / Instagram API version is supported by this package?

**Comment by biapar** [comment]
Is't possible to edit the documentation on https://social.skybrud.dk?
I think that there are some issues and it's not updated.

**Comment by abjerner** [comment]
Unfortunately they are not stored in a format that allows editing/contributions. It probably should though, but that would require quite some work.

If you see examples that you think are wrong or not up to date, you're more than welcome to report it here on GitHub, and I'll look into it. That's the best I can do a the moment.
