### ISSUE TITLE
OAuthRequestToken is not serializable

### ISSUE THREAD

**Issue by digbyswift** [abjerner/Skybrud.Social#87]
We are trying to use Skybrud.Social.Umbraco v0.9.6 with an existing v7 site hosted on Azure using Redis as sessionState backing.

When the app authorization callback (https://site.local/App_Plugins/Skybrud.Social/Dialogs/TwitterOAuth.aspx) is performed, the package attempts to store the token in session state but this fails with the following exception:

> SerializationException: Type 'Skybrud.Social.OAuth.OAuthRequestToken' in Assembly 'Skybrud.Social, Version=0.9.6.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.]
   System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type) +12685645
   System.Runtime.Serialization.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _) +40
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +72
   System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context) +174
   System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo() +159
   System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder) +178
   System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder) +51
   System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck) +540
   System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck) +131

I have switched back to test standard session state and this works fine as expected, but this isn't appropriate for the application.

I'm assuming that it's because the class has an internal constructor, rather than it not being makred as serializable but can you suggest any way to avoid this error?

**Comment by abjerner** [comment]
Hi @digbyswift and thanks for reporting 👍

The classes in Skybrud.Social were never designed to be serialized this way, and I haven't worked with binary serialization for quite some time, so I'm not sure how best to fix this. Your issue also very much an edge case (you're the first to report this in the five years the Umbraco 7 package has existed), so this is not something I will work on a fix for (both Skybrud.Social and the Umbraco 7 package are no longer in active development).

But if there is an easy fix, you're more than welcome two submit a PR, and I'd be happy to look into it 😉
